source: 'src'
title: CSDU Unofficial
url: 'https://ducs.in/csdu-jekyll-website'

plugins:
    - jekyll-postcss
    - jekyll-purgecss

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - tailwind.config.js
    - postcss.config.js
    - purgecss.config.js
    - package.json
    - package-lock.json
